/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as PrinterRouteImport } from './routes/printer'
import { Route as PrintRouteImport } from './routes/print'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as KioskRouteImport } from './routes/kiosk'
import { Route as CameraTestRouteImport } from './routes/camera-test'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PrinterSetupRouteImport } from './routes/printer.setup'

const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const PrinterRoute = PrinterRouteImport.update({
  id: '/printer',
  path: '/printer',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintRoute = PrintRouteImport.update({
  id: '/print',
  path: '/print',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const KioskRoute = KioskRouteImport.update({
  id: '/kiosk',
  path: '/kiosk',
  getParentRoute: () => rootRouteImport,
} as any)
const CameraTestRoute = CameraTestRouteImport.update({
  id: '/camera-test',
  path: '/camera-test',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrinterSetupRoute = PrinterSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => PrinterRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/camera-test': typeof CameraTestRoute
  '/kiosk': typeof KioskRoute
  '/pricing': typeof PricingRoute
  '/print': typeof PrintRoute
  '/printer': typeof PrinterRouteWithChildren
  '/studio': typeof StudioRoute
  '/printer/setup': typeof PrinterSetupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/camera-test': typeof CameraTestRoute
  '/kiosk': typeof KioskRoute
  '/pricing': typeof PricingRoute
  '/print': typeof PrintRoute
  '/printer': typeof PrinterRouteWithChildren
  '/studio': typeof StudioRoute
  '/printer/setup': typeof PrinterSetupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/camera-test': typeof CameraTestRoute
  '/kiosk': typeof KioskRoute
  '/pricing': typeof PricingRoute
  '/print': typeof PrintRoute
  '/printer': typeof PrinterRouteWithChildren
  '/studio': typeof StudioRoute
  '/printer/setup': typeof PrinterSetupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/camera-test'
    | '/kiosk'
    | '/pricing'
    | '/print'
    | '/printer'
    | '/studio'
    | '/printer/setup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/camera-test'
    | '/kiosk'
    | '/pricing'
    | '/print'
    | '/printer'
    | '/studio'
    | '/printer/setup'
  id:
    | '__root__'
    | '/'
    | '/camera-test'
    | '/kiosk'
    | '/pricing'
    | '/print'
    | '/printer'
    | '/studio'
    | '/printer/setup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CameraTestRoute: typeof CameraTestRoute
  KioskRoute: typeof KioskRoute
  PricingRoute: typeof PricingRoute
  PrintRoute: typeof PrintRoute
  PrinterRoute: typeof PrinterRouteWithChildren
  StudioRoute: typeof StudioRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/printer': {
      id: '/printer'
      path: '/printer'
      fullPath: '/printer'
      preLoaderRoute: typeof PrinterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print': {
      id: '/print'
      path: '/print'
      fullPath: '/print'
      preLoaderRoute: typeof PrintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kiosk': {
      id: '/kiosk'
      path: '/kiosk'
      fullPath: '/kiosk'
      preLoaderRoute: typeof KioskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/camera-test': {
      id: '/camera-test'
      path: '/camera-test'
      fullPath: '/camera-test'
      preLoaderRoute: typeof CameraTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/printer/setup': {
      id: '/printer/setup'
      path: '/setup'
      fullPath: '/printer/setup'
      preLoaderRoute: typeof PrinterSetupRouteImport
      parentRoute: typeof PrinterRoute
    }
  }
}

interface PrinterRouteChildren {
  PrinterSetupRoute: typeof PrinterSetupRoute
}

const PrinterRouteChildren: PrinterRouteChildren = {
  PrinterSetupRoute: PrinterSetupRoute,
}

const PrinterRouteWithChildren =
  PrinterRoute._addFileChildren(PrinterRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CameraTestRoute: CameraTestRoute,
  KioskRoute: KioskRoute,
  PricingRoute: PricingRoute,
  PrintRoute: PrintRoute,
  PrinterRoute: PrinterRouteWithChildren,
  StudioRoute: StudioRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
